# Form implementation generated from reading ui file 'front-end.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow, data):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(374, 531)
        MainWindow.setStyleSheet("background-color: #5d5d5d;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listView = QtWidgets.QListView(parent=self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(0, -90, 381, 651))
        self.listView.setObjectName("listView")
        self.columnView = QtWidgets.QColumnView(parent=self.centralwidget)
        self.columnView.setGeometry(QtCore.QRect(20, 10, 331, 151))
        self.columnView.setStyleSheet("background-color: #000;\n" "border-radius: 9px;")
        self.columnView.setObjectName("columnView")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 121, 131))
        self.label.setStyleSheet("border-radius: 33px;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("./img/pexels-saveurs-secretes-5410400.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(160, 20, 171, 51))
        self.label_2.setStyleSheet(
            "font-size: 17px;\n" "color: #fff;\n" "background-color: #000;"
        )
        self.label_2.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading
            | QtCore.Qt.AlignmentFlag.AlignLeft
            | QtCore.Qt.AlignmentFlag.AlignTop
        )
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(90, 30, 51, 21))
        self.label_3.setStyleSheet(
            "font-size: 9px;\n" "color: #fff;\n" "background-color: #000;"
        )
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(160, 50, 16, 16))
        self.label_4.setStyleSheet("background-color: #000;")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("./img/star-fill.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(180, 50, 16, 16))
        self.label_5.setStyleSheet("background-color: #000;")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("./img/star-fill.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(200, 50, 16, 16))
        self.label_6.setStyleSheet("background-color: #000;")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("./img/star-fill.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(220, 50, 16, 16))
        self.label_7.setStyleSheet("background-color: #000;")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("./img/star-fill.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(240, 50, 16, 16))
        self.label_8.setStyleSheet("background-color: #000;")
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("./img/star-empty.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(160, 80, 16, 16))
        self.label_9.setStyleSheet("background-color: #000;")
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("./img/map.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(180, 80, 141, 41))
        self.label_10.setStyleSheet(
            "font-size: 13px;\n" "color: #d9d9d9;\n" "background-color: #000;"
        )
        self.label_10.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading
            | QtCore.Qt.AlignmentFlag.AlignLeft
            | QtCore.Qt.AlignmentFlag.AlignTop
        )
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(160, 130, 51, 21))
        self.label_11.setStyleSheet(
            "font-size: 10px;\n"
            "font-weight: 600;\n"
            "color: #000;\n"
            "background-color: #d9d9d9;"
        )
        self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(315, 130, 21, 20))
        self.label_12.setStyleSheet("background-color: #000;")
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("./img/visit.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.label_19 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(20, 180, 121, 131))
        self.label_19.setStyleSheet("border-radius: 33px;")
        self.label_19.setText("")
        self.label_19.setPixmap(
            QtGui.QPixmap("./img/pexels-saveurs-secretes-5410400.jpg")
        )
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName("label_19")
        self.label_17 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(20, 180, 121, 131))
        self.label_17.setStyleSheet("border-radius: 33px;")
        self.label_17.setText("")
        self.label_17.setPixmap(
            QtGui.QPixmap("./img/pexels-saveurs-secretes-5410400.jpg")
        )
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.label_13 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(160, 250, 16, 16))
        self.label_13.setStyleSheet("background-color: #000;")
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("./img/map.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(240, 220, 16, 16))
        self.label_14.setStyleSheet("background-color: #000;")
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("./img/star-empty.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(180, 220, 16, 16))
        self.label_15.setStyleSheet("background-color: #000;")
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("./img/star-fill.png"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(315, 300, 21, 20))
        self.label_16.setStyleSheet("background-color: #000;")
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("./img/visit.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.label_18 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(30, 190, 121, 131))
        self.label_18.setStyleSheet("border-radius: 33px;")
        self.label_18.setText("")
        self.label_18.setPixmap(
            QtGui.QPixmap("./img/pexels-saveurs-secretes-5410400.jpg")
        )
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName("label_18")
        self.label_20 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(160, 220, 16, 16))
        self.label_20.setStyleSheet("background-color: #000;")
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap("./img/star-fill.png"))
        self.label_20.setScaledContents(True)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(200, 220, 16, 16))
        self.label_21.setStyleSheet("background-color: #000;")
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap("./img/star-fill.png"))
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName("label_21")
        self.columnView_2 = QtWidgets.QColumnView(parent=self.centralwidget)
        self.columnView_2.setGeometry(QtCore.QRect(20, 180, 331, 151))
        self.columnView_2.setStyleSheet(
            "background-color: #000;\n" "border-radius: 9px;"
        )
        self.columnView_2.setObjectName("columnView_2")
        self.label_22 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(220, 220, 16, 16))
        self.label_22.setStyleSheet("background-color: #000;")
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap("./img/star-fill.png"))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(160, 300, 51, 21))
        self.label_23.setStyleSheet(
            "font-size: 10px;\n"
            "font-weight: 600;\n"
            "color: #000;\n"
            "background-color: #d9d9d9;"
        )
        self.label_23.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_23.setWordWrap(True)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(90, 200, 51, 21))
        self.label_24.setStyleSheet(
            "font-size: 9px;\n" "color: #fff;\n" "background-color: #000;"
        )
        self.label_24.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_24.setWordWrap(True)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(180, 250, 141, 41))
        self.label_25.setStyleSheet(
            "font-size: 13px;\n" "color: #d9d9d9;\n" "background-color: #000;"
        )
        self.label_25.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading
            | QtCore.Qt.AlignmentFlag.AlignLeft
            | QtCore.Qt.AlignmentFlag.AlignTop
        )
        self.label_25.setWordWrap(True)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(30, 190, 121, 131))
        self.label_26.setStyleSheet("border-radius: 33px;")
        self.label_26.setText("")
        self.label_26.setPixmap(
            QtGui.QPixmap("./img/pexels-saveurs-secretes-5410400.jpg")
        )
        self.label_26.setScaledContents(True)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(160, 190, 171, 51))
        self.label_27.setStyleSheet(
            "font-size: 17px;\n" "color: #fff;\n" "background-color: #000;"
        )
        self.label_27.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading
            | QtCore.Qt.AlignmentFlag.AlignLeft
            | QtCore.Qt.AlignmentFlag.AlignTop
        )
        self.label_27.setWordWrap(True)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(160, 410, 16, 16))
        self.label_28.setStyleSheet("background-color: #000;")
        self.label_28.setText("")
        self.label_28.setPixmap(QtGui.QPixmap("./img/map.png"))
        self.label_28.setScaledContents(True)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(240, 380, 16, 16))
        self.label_29.setStyleSheet("background-color: #000;")
        self.label_29.setText("")
        self.label_29.setPixmap(QtGui.QPixmap("./img/star-empty.png"))
        self.label_29.setScaledContents(True)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(180, 380, 16, 16))
        self.label_30.setStyleSheet("background-color: #000;")
        self.label_30.setText("")
        self.label_30.setPixmap(QtGui.QPixmap("./img/star-fill.png"))
        self.label_30.setScaledContents(True)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(315, 460, 21, 20))
        self.label_31.setStyleSheet("background-color: #000;")
        self.label_31.setText("")
        self.label_31.setPixmap(QtGui.QPixmap("./img/visit.png"))
        self.label_31.setScaledContents(True)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(30, 350, 121, 131))
        self.label_32.setStyleSheet("border-radius: 33px;")
        self.label_32.setText("")
        self.label_32.setPixmap(
            QtGui.QPixmap("./img/pexels-saveurs-secretes-5410400.jpg")
        )
        self.label_32.setScaledContents(True)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(160, 380, 16, 16))
        self.label_33.setStyleSheet("background-color: #000;")
        self.label_33.setText("")
        self.label_33.setPixmap(QtGui.QPixmap("./img/star-fill.png"))
        self.label_33.setScaledContents(True)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(200, 380, 16, 16))
        self.label_34.setStyleSheet("background-color: #000;")
        self.label_34.setText("")
        self.label_34.setPixmap(QtGui.QPixmap("./img/star-fill.png"))
        self.label_34.setScaledContents(True)
        self.label_34.setObjectName("label_34")
        self.columnView_3 = QtWidgets.QColumnView(parent=self.centralwidget)
        self.columnView_3.setGeometry(QtCore.QRect(20, 340, 331, 151))
        self.columnView_3.setStyleSheet(
            "background-color: #000;\n" "border-radius: 9px;"
        )
        self.columnView_3.setObjectName("columnView_3")
        self.label_35 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(160, 350, 171, 51))
        self.label_35.setStyleSheet(
            "font-size: 17px;\n" "color: #fff;\n" "background-color: #000;"
        )
        self.label_35.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading
            | QtCore.Qt.AlignmentFlag.AlignLeft
            | QtCore.Qt.AlignmentFlag.AlignTop
        )
        self.label_35.setWordWrap(True)
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(220, 380, 16, 16))
        self.label_36.setStyleSheet("background-color: #000;")
        self.label_36.setText("")
        self.label_36.setPixmap(QtGui.QPixmap("./img/star-fill.png"))
        self.label_36.setScaledContents(True)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(160, 460, 51, 21))
        self.label_37.setStyleSheet(
            "font-size: 10px;\n"
            "font-weight: 600;\n"
            "color: #000;\n"
            "background-color: #d9d9d9;"
        )
        self.label_37.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_37.setWordWrap(True)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(90, 360, 51, 21))
        self.label_38.setStyleSheet(
            "font-size: 9px;\n" "color: #fff;\n" "background-color: #000;"
        )
        self.label_38.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_38.setWordWrap(True)
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_39.setGeometry(QtCore.QRect(180, 410, 141, 41))
        self.label_39.setStyleSheet(
            "font-size: 13px;\n" "color: #d9d9d9;\n" "background-color: #000;"
        )
        self.label_39.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading
            | QtCore.Qt.AlignmentFlag.AlignLeft
            | QtCore.Qt.AlignmentFlag.AlignTop
        )
        self.label_39.setWordWrap(True)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_40.setGeometry(QtCore.QRect(30, 350, 121, 131))
        self.label_40.setStyleSheet("border-radius: 33px;")
        self.label_40.setText("")
        self.label_40.setPixmap(
            QtGui.QPixmap("./img/pexels-saveurs-secretes-5410400.jpg")
        )
        self.label_40.setScaledContents(True)
        self.label_40.setObjectName("label_40")
        self.listView.raise_()
        self.columnView.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_19.raise_()
        self.label_17.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.label_18.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        self.columnView_2.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.label_25.raise_()
        self.label_26.raise_()
        self.label_24.raise_()
        self.label_27.raise_()
        self.label_28.raise_()
        self.label_29.raise_()
        self.label_30.raise_()
        self.label_31.raise_()
        self.label_32.raise_()
        self.label_33.raise_()
        self.label_34.raise_()
        self.columnView_3.raise_()
        self.label_35.raise_()
        self.label_36.raise_()
        self.label_37.raise_()
        self.label_39.raise_()
        self.label_40.raise_()
        self.label_38.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 374, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow, data)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow, data):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        text_labels = [self.label_2, self.label_27, self.label_35]
        address_labels = [self.label_10, self.label_25, self.label_39]
        ratings_labels = [self.label_11, self.label_23, self.label_37]
        status_labels = [self.label_3, self.label_24, self.label_38]

        i = 0
        print(len(data))
        print(data)
        j = 0
        while i < len(text_labels) and j < len(data):
            dt = data[j]
            j += 1
            text_labels[i].setText(_translate("MainWindow", dt["text"]))
            ratings_labels[i].setText(_translate("MainWindow", dt["rating"]))
            try:
                address_labels[i].setText(_translate("MainWindow", dt["address"]))
            except:
                continue

            try:
                status_labels[i].setText(_translate("MainWindow", dt["status"]))
            except KeyError:
                status_labels[i].setText(_translate("MainWindow", "Closed"))
            i += 1

        # i -= 1
        print("text : ", address_labels[i].text())
        while address_labels[i].text() == "":
            address_labels[i].setText(_translate("MainWindow", "Location Not Found"))
            status_labels[i].setText(_translate("MainWindow", "Closed"))
            i -= 1
        # self.label_2.setText()
        # self.label_3.setText(_translate("MainWindow", "Open Now"))
        # self.label_10.setText(_translate("MainWindow", "Chintamani Nagar, Pune 411037"))
        # self.label_11.setText(_translate("MainWindow", "4 km"))
        # self.label_23.setText(_translate("MainWindow", "4 km"))
        # self.label_24.setText(_translate("MainWindow", "Open Now"))
        # self.label_25.setText(_translate("MainWindow", "Chintamani Nagar, Pune 411037"))
        # self.label_27.setText(_translate("MainWindow", "Sukhsagar Pavbhaji"))
        # self.label_35.setText(_translate("MainWindow", "Sukhsagar Pavbhaji"))
        # self.label_37.setText(_translate("MainWindow", "4 km"))
        # self.label_38.setText(_translate("MainWindow", "Open Now"))
        # self.label_39.setText(_translate("MainWindow", "Chintamani Nagar, Pune 411037"))
